#!/usr/bin/env bash

source "$HOME"/.shellrc

HISTFILESIZE=-1
HISTSIZE=-1
HISTCONTROL=ignoreboth

shopt -u histappend

if [ -f /usr/share/bash-completion/completions/git ]; then
  source /usr/share/bash-completion/completions/git

  __git_complete gap _git_add
  __git_complete gb _git_branch
  __git_complete gca _git_commit
  __git_complete gco _git_checkout
  __git_complete gcp _git_checkout
  __git_complete gcv _git_commit
  __git_complete gd _git_diff
  __git_complete gfo _git_fetch
  __git_complete gpu _git_push
  __git_complete grc _git_rebase
  __git_complete gs _git_status
fi

if command -v b4 > /dev/null 2>&1; then
  eval "$(b4 --print-completion bash)"
fi

if command -v codex >/dev/null 2>&1; then
  eval "$(codex completion bash)"
fi

if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook bash)"
fi

if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate bash)"
fi

# OpenAI shrc (if customising, comment out to prevent it getting readded)
# for file in "/Users/tamird/.openai/shrc"/*; do
#     source "$file"
# done
